export const RATE_LIMIT_CAPACITY = Symbol('RATE_LIMIT_CAPACITY');
export const RATE_LIMIT_REFILL_PER_SECOND = Symbol('RATE_LIMIT_REFILL_PER_SECOND');
export const RATE_LIMIT_CLOCK = Symbol('RATE_LIMIT_CLOCK');
